avator_2:
 preparation: True # your can set it to False if you want to use the existing avator, it will save time
 bbox_shift: 5
 video_path: "data/video/yongen.mp4"
 audio_clips:
    audio_0.0: "data/audio/yongen.wav_0.0"
    audio_0.1: "data/audio/yongen.wav_0.1"
    audio_0.2: "data/audio/yongen.wav_0.2"
    audio_0.3: "data/audio/yongen.wav_0.3"
    audio_0.4: "data/audio/yongen.wav_0.4"
    audio_0.5: "data/audio/yongen.wav_0.5"
    audio_0.6: "data/audio/yongen.wav_0.6"
    audio_0.7: "data/audio/yongen.wav_0.7"
    audio_0.8: "data/audio/yongen.wav_0.8"
    audio_0.9: "data/audio/yongen.wav_0.9"
    audio_1.0: "data/audio/yongen.wav_1.0"
    audio_1.1: "data/audio/yongen.wav_1.1"
    audio_1.2: "data/audio/yongen.wav_1.2"
    audio_1.3: "data/audio/yongen.wav_1.3"
    audio_1.4: "data/audio/yongen.wav_1.4"
    audio_1.5: "data/audio/yongen.wav_1.5"
    audio_1.6: "data/audio/yongen.wav_1.6"
    audio_1.7: "data/audio/yongen.wav_1.7"
    audio_1.8: "data/audio/yongen.wav_1.8"
    audio_1.9: "data/audio/yongen.wav_1.9"
    audio_2.0: "data/audio/yongen.wav_2.0"
    audio_2.1: "data/audio/yongen.wav_2.1"
    audio_2.2: "data/audio/yongen.wav_2.2"
    audio_2.3: "data/audio/yongen.wav_2.3"
    audio_2.4: "data/audio/yongen.wav_2.4"
    audio_2.5: "data/audio/yongen.wav_2.5"
    audio_2.6: "data/audio/yongen.wav_2.6"
    audio_2.7: "data/audio/yongen.wav_2.7"
    audio_2.8: "data/audio/yongen.wav_2.8"
    audio_2.9: "data/audio/yongen.wav_2.9"
    audio_3.0: "data/audio/yongen.wav_3.0"
    audio_3.1: "data/audio/yongen.wav_3.1"
    audio_3.2: "data/audio/yongen.wav_3.2"
    audio_3.3: "data/audio/yongen.wav_3.3"
    audio_3.4: "data/audio/yongen.wav_3.4"
    audio_3.5: "data/audio/yongen.wav_3.5"
    audio_3.6: "data/audio/yongen.wav_3.6"
    audio_3.7: "data/audio/yongen.wav_3.7"
    audio_3.8: "data/audio/yongen.wav_3.8"
    audio_3.9: "data/audio/yongen.wav_3.9"
    audio_4.0: "data/audio/yongen.wav_4.0"
    audio_4.1: "data/audio/yongen.wav_4.1"
    audio_4.2: "data/audio/yongen.wav_4.2"
    audio_4.3: "data/audio/yongen.wav_4.3"
    audio_4.4: "data/audio/yongen.wav_4.4"
    audio_4.5: "data/audio/yongen.wav_4.5"
    audio_4.6: "data/audio/yongen.wav_4.6"
    audio_4.7: "data/audio/yongen.wav_4.7"
    audio_4.8: "data/audio/yongen.wav_4.8"
    audio_4.9: "data/audio/yongen.wav_4.9"
    audio_5.0: "data/audio/yongen.wav_5.0"
    audio_5.1: "data/audio/yongen.wav_5.1"
    audio_5.2: "data/audio/yongen.wav_5.2"
    audio_5.3: "data/audio/yongen.wav_5.3"
    audio_5.4: "data/audio/yongen.wav_5.4"
    audio_5.5: "data/audio/yongen.wav_5.5"
    audio_5.6: "data/audio/yongen.wav_5.6"
    audio_5.7: "data/audio/yongen.wav_5.7"
    audio_5.8: "data/audio/yongen.wav_5.8"
    audio_5.9: "data/audio/yongen.wav_5.9"
    audio_6.0: "data/audio/yongen.wav_6.0"
    audio_6.1: "data/audio/yongen.wav_6.1"
    audio_6.2: "data/audio/yongen.wav_6.2"
    audio_6.3: "data/audio/yongen.wav_6.3"
    audio_6.4: "data/audio/yongen.wav_6.4"
    audio_6.5: "data/audio/yongen.wav_6.5"
    audio_6.6: "data/audio/yongen.wav_6.6"
    audio_6.7: "data/audio/yongen.wav_6.7"
    audio_6.8: "data/audio/yongen.wav_6.8"
    audio_6.9: "data/audio/yongen.wav_6.9"
    audio_7.0: "data/audio/yongen.wav_7.0"
    audio_7.1: "data/audio/yongen.wav_7.1"
    audio_7.2: "data/audio/yongen.wav_7.2"
    audio_7.3: "data/audio/yongen.wav_7.3"
    audio_7.4: "data/audio/yongen.wav_7.4"
    audio_7.5: "data/audio/yongen.wav_7.5"
    audio_7.6: "data/audio/yongen.wav_7.6"
    audio_7.7: "data/audio/yongen.wav_7.7"
    audio_7.8: "data/audio/yongen.wav_7.8"
    

    audio2_0.0: "data/audio/engshort.wav_0.0"
    audio2_0.1: "data/audio/engshort.wav_0.1"
    audio2_0.2: "data/audio/engshort.wav_0.2"
    audio2_0.3: "data/audio/engshort.wav_0.3"
    audio2_0.4: "data/audio/engshort.wav_0.4"
    audio2_0.5: "data/audio/engshort.wav_0.5"
    audio2_0.6: "data/audio/engshort.wav_0.6"
    audio2_0.7: "data/audio/engshort.wav_0.7"
    audio2_0.8: "data/audio/engshort.wav_0.8"
    audio2_0.9: "data/audio/engshort.wav_0.9"
    audio2_1.0: "data/audio/engshort.wav_1.0"
    audio2_1.1: "data/audio/engshort.wav_1.1"
    audio2_1.2: "data/audio/engshort.wav_1.2"
    audio2_1.3: "data/audio/engshort.wav_1.3"
    audio2_1.4: "data/audio/engshort.wav_1.4"
    audio2_1.5: "data/audio/engshort.wav_1.5"
    audio2_1.6: "data/audio/engshort.wav_1.6"
    audio2_1.7: "data/audio/engshort.wav_1.7"
    audio2_1.8: "data/audio/engshort.wav_1.8"
    audio2_1.9: "data/audio/engshort.wav_1.9"
    audio2_2.0: "data/audio/engshort.wav_2.0"
    audio2_2.1: "data/audio/engshort.wav_2.1"
    audio2_2.2: "data/audio/engshort.wav_2.2"
    audio2_2.3: "data/audio/engshort.wav_2.3"
    audio2_2.4: "data/audio/engshort.wav_2.4"
    audio2_2.5: "data/audio/engshort.wav_2.5"
    audio2_2.6: "data/audio/engshort.wav_2.6"
    audio2_2.7: "data/audio/engshort.wav_2.7"
    audio2_2.8: "data/audio/engshort.wav_2.8"
    audio2_2.9: "data/audio/engshort.wav_2.9"
    audio2_3.0: "data/audio/engshort.wav_3.0"
    audio2_3.1: "data/audio/engshort.wav_3.1"
    audio2_3.2: "data/audio/engshort.wav_3.2"
    audio2_3.3: "data/audio/engshort.wav_3.3"
    audio2_3.4: "data/audio/engshort.wav_3.4"
    audio2_3.5: "data/audio/engshort.wav_3.5"
    audio2_3.6: "data/audio/engshort.wav_3.6"
    audio2_3.7: "data/audio/engshort.wav_3.7"
    audio2_3.8: "data/audio/engshort.wav_3.8"
    audio2_3.9: "data/audio/engshort.wav_3.9"
    audio2_4.0: "data/audio/engshort.wav_4.0"
    audio2_4.1: "data/audio/engshort.wav_4.1"
    audio2_4.2: "data/audio/engshort.wav_4.2"
    audio2_4.3: "data/audio/engshort.wav_4.3"
    audio2_4.4: "data/audio/engshort.wav_4.4"
    audio2_4.5: "data/audio/engshort.wav_4.5"
    audio2_4.6: "data/audio/engshort.wav_4.6"
    audio2_4.7: "data/audio/engshort.wav_4.7"
    audio2_4.8: "data/audio/engshort.wav_4.8"
    audio2_4.9: "data/audio/engshort.wav_4.9"
    audio2_5.0: "data/audio/engshort.wav_5.0"
    audio2_5.1: "data/audio/engshort.wav_5.1"
    audio2_5.2: "data/audio/engshort.wav_5.2"
    audio2_5.3: "data/audio/engshort.wav_5.3"
    audio2_5.4: "data/audio/engshort.wav_5.4"
    audio2_5.5: "data/audio/engshort.wav_5.5"
    audio2_5.6: "data/audio/engshort.wav_5.6"
    audio2_5.7: "data/audio/engshort.wav_5.7"
    audio2_5.8: "data/audio/engshort.wav_5.8"
    audio2_5.9: "data/audio/engshort.wav_5.9"
    audio2_6.0: "data/audio/engshort.wav_6.0"
    audio2_6.1: "data/audio/engshort.wav_6.1"
    audio2_6.2: "data/audio/engshort.wav_6.2"
    audio2_6.3: "data/audio/engshort.wav_6.3"
    audio2_6.4: "data/audio/engshort.wav_6.4"
    audio2_6.5: "data/audio/engshort.wav_6.5"
    audio2_6.6: "data/audio/engshort.wav_6.6"
    audio2_6.7: "data/audio/engshort.wav_6.7"
    audio2_6.8: "data/audio/engshort.wav_6.8"
    audio2_6.9: "data/audio/engshort.wav_6.9"
    audio2_7.0: "data/audio/engshort.wav_7.0"
    audio2_7.1: "data/audio/engshort.wav_7.1"
    audio2_7.2: "data/audio/engshort.wav_7.2"
    audio2_7.3: "data/audio/engshort.wav_7.3"
    audio2_7.4: "data/audio/engshort.wav_7.4"
    audio2_7.5: "data/audio/engshort.wav_7.5"
    audio2_7.6: "data/audio/engshort.wav_7.6"
    audio2_7.7: "data/audio/engshort.wav_7.7"
    audio2_7.8: "data/audio/engshort.wav_7.8"

  

