#pmilos: this is a config for training on one GPU
compute_environment: LOCAL_MACHINE
debug: True
distributed_type: NO # Set to NO for a single-process, non-distributed run.
downcast_bf16: 'no'
gpu_ids: "0" # Specify the single GPU to use.
machine_rank: 0
main_training_function: main
num_machines: 1
num_processes: 1 # Ensure this matches the single GPU.
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false